server:
  port: 3001
spring:
  application:
    # 服务名
    name: user-service
#注册到EurekaServer
eureka:
  client:
    serviceUrl:
# Eureka服务端注册中心的地址
      defaultZone: http://localhost:1000/eureka/
  instance:
#    用ip注册 不使用主机名注册
    prefer-ip-address: true
#    实例的唯一标识
    instance-id: user:3001

